Watching for file changes with StatReloader
Forbidden: /accounts/profile/
Not Found: /course/courses/
Forbidden: /vacancy/1/delete/
Not Found: /vacancy/2/
Not Found: /api/applications/1/
Not Found: /api/applications/employer/
Not Found: /api/applications/user/
Not Found: /api/applications/1/
Not Found: /api/applications/employer/
Not Found: /api/applications/user/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
Watching for file changes with StatReloader
Forbidden: /vacancy/
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden: /vacancy/
Forbidden: /vacancy/
Forbidden: /vacancy/
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden: /vacancy/
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden: /vacancy/
Forbidden: /vacancy/
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /vacancy/create/
Watching for file changes with StatReloader
Forbidden: /vacancy/create/
Method Not Allowed: /vacancy/create/
Forbidden: /vacancy/create/
Forbidden: /vacancy/create/
Forbidden: /vacancy/create/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/delete/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/delete/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/delete/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Forbidden: /vacancy/1/delete/
Forbidden: /vacancy/1/edit/
Forbidden: /vacancy/create/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/resume_builder/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /vacancy/vacancies-analytics/
Traceback (most recent call last):
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/views.py", line 27, in vacancies_analytics
    return render(request, 'vacancies/analytics.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vennv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'vacancies_per_month_api' not found. 'vacancies_per_month_api' is not a valid view function or pattern name.
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/rustemtemirgali/Desktop/kbtu3_5s/Django2024/final_project/Django-project/vacancies/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
/Users/alua/Desktop/Django-project/resume_builder/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden: /accounts/profile/
Forbidden: /accounts/profile/
Internal Server Error: /pdf/resume/
Traceback (most recent call last):
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/pdf_generator/urls.py", line 5, in <lambda>
    path('resume/', lambda r: generate_pdf(r, 'resume_template.html'), name='generate_resume_pdf'),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/pdf_generator/views.py", line 26, in generate_pdf
    template = get_template(f'pdf_templates/{template_name}')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: pdf_templates/resume_template.html
/Users/alua/Desktop/Django-project/resume_builder/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /pdf/resume/
Traceback (most recent call last):
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/pdf_generator/urls.py", line 5, in <lambda>
    path('resume/', lambda r: generate_pdf(r, 'resume_template.html'), name='generate_resume_pdf'),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/pdf_generator/views.py", line 26, in generate_pdf
    template = get_template(f'pdf_templates/{template_name}')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: pdf_templates/resume_template.html
Internal Server Error: /pdf/resume/
Traceback (most recent call last):
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/pdf_generator/urls.py", line 5, in <lambda>
    path('resume/', lambda r: generate_pdf(r, 'resume_template.html'), name='generate_resume_pdf'),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/pdf_generator/views.py", line 26, in generate_pdf
    template = get_template(f'pdf_templates/{template_name}')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alua/Desktop/Django-project/venvr/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: pdf_templates/resume_template.html
